version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    container_name: workspace
    volumes:
      - ./workspace:/workspace
    tty: true
    command: >
      zsh -c '
      . ~/.profile
      '